enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Music-Extended]
app-name = "Music"
patches-source = "Blawuken/revanced-patches-extended"
integrations-source = "Blawuken/revanced-integrations-extended"
cli-source = "ReVanced/revanced-cli"
rv-brand = "Extended"
build-mode = "both"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[YouTube-Extended]
app-name = "YouTube"
patches-source = "Blawuken/revanced-patches-extended"
integrations-source = "Blawuken/revanced-integrations-extended"
cli-source = "ReVanced/revanced-cli"
rv-brand = "Extended"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
