enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Music-Extended-arm]
app-name = "Music"
patches-source = "Blawuken/revanced-patches-extended"
integrations-source = "Blawuken/revanced-integrations-extended"
cli-source = "Blawuken/revanced-cli-extended"
rv-brand = "Extended"
build-mode = "apk"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
arch = "both"
