name: Act on release

on: 
  workflow_call:
    secrets:
      TELEGRAM_TO:
        required: true
      TELEGRAM_TOKEN:
        required: true
  workflow_dispatch:
      

jobs:
  Notify_Release:
    name: Notify Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Telegram Channel Update
        run: |
          telegram_message() {
               curl -v "https://api.telegram.org/bot""$TELEGRAM_TOKEN""/sendPhoto?chat_id=""$TELEGRAM_TO""$ARGS_EXTRA" -H 'Content-Type: multipart/form-data' \
               --form photo="https://telegra.ph/file/095a9dbcc129453a28c12.png" \
               -F "parse_mode=html" \
               -F caption="$1"
          }
          
          TG_TEXT="$(< release_notification.md)"
          telegram_message "$TG_TEXT"
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
